package com.example.administrator.zhixueproject.http;

public class HandlerConstant2 {

    public static final int GET_TOPIC_LIST_SUCCESS=2000;
    public static final int GET_TOPIC_LIST_SUCCESS2=2001;
    public static final int MODIFY_USER_INFO_SUCCESS = 2002;
    public static final int IS_UP_OR_DOWN_SUCCESS = 2003;
    public static final int IS_UP_OR_DOWN_SUCCESS2 = 2004;
    public static final int UPDATE_SORT_SUCCESS = 2005;
    public static final int ADD_TOPIC_SUCCESS = 2006;
    public static final int UPDATE_TOPIC_SUCCESS = 2007;
    public static final int GET_POST_LIST_SUCCESS1 = 2008;
    public static final int GET_POST_LIST_SUCCESS2 = 2009;
    public static final int GET_POST_LIST_SEARCH_SUCCESS1 = 2010;
    public static final int GET_POST_LIST_SEARCH_SUCCESS2 = 2011;
    public static final int GET_LECTURERS_LIST_SUCCESS1 = 2012;
    public static final int GET_LECTURERS_LIST_SUCCESS2 = 2013;
    public static final int ADD_POST_SUCCESS = 2014;
    public static final int UPDATE_POST_SUCCESS = 2015;
    public static final int ADD_ACTIVITY_SUCCESS = 2016;
    public static final int UPDATE_ACTIVITY_SUCCESS = 2017;
    public static final int ADD_VOTE_SUCCESS = 2018;
    public static final int COMMENT_POST_SUCCESS = 2019;
    public static final int COMMENT_REPLY_SUCCESS =2020 ;
    public static final int GET_POST_DETAIL_SUCCESS = 2021;
    public static final int GET_POST_DETAIL_SUCCESS2 = 2022;
    public static final int GET_YOU_CHANG_DETAIL_SUCCESS =2023 ;
    public static final int GET_ACTIVITY_LIST_SUCCESS = 2024;
    public static final int GET_ACTIVITY_LIST_SUCCESS2 = 2025;
    public static final int DELETE_ACTIVITY_SUCCESS = 2026;
    public static final int GET_ACTIVITY_USER_LIST_SUCCESS = 2027;
    public static final int GET_ACTIVITY_USER_LIST_SUCCESS2 = 2028;
    public static final int GET_VOTE_LIST_SUCCESS = 2029;
    public static final int GET_VOTE_LIST_SUCCESS2 = 2030;
    public static final int DELETE_VOTE_SUCCESS = 2031;
    public static final int GET_VOTE_USER_LIST_SUCCESS = 2032;
    public static final int GET_VOTE_USER_LIST_SUCCESS2 = 2033;
    public static final int GET_VIP_LIST_SUCCESS1 = 2034;
    public static final int GET_VIP_LIST_SUCCESS2 = 2035;
    public static final int KICK_OUT_VIP_SUCCESS = 2036;
    public static final int GET_VIP_INFO_SUCCESS = 2037;
    public static final int GET_VIP_INFO_SUCCESS2 = 2038;
    public static final int SAVE_VIP_SUCCESS = 2039;
    public static final int GET_APPLY_VIP_LIST_SUCCESS = 2040;
    public static final int GET_APPLY_VIP_LIST_SUCCESS2 = 2041;
    public static final int APPLY_REFUSE_SUCCESS = 2042;
    public static final int GET_DELYN_VIP_LIST_SUCCESS =2043 ;
    public static final int GET_DELYN_VIP_LIST_SUCCESS2 = 2044;
    public static final int DELYN_VIP_INVITE_SUCCESS = 2045;
    public static final int REMOVE_BLACK_LIST_SUCCESS = 2046;
    public static final int GET_BLACK_LIST_SUCCESS = 2047;
    public static final int GET_BLACK_LIST_SUCCESS2 = 2048;
    public static final int DELETE_VOTE_MEMBER_SUCCESS = 2049;
    public static final int APPLY_PASS_SUCCESS = 2050;
    public static final int UPDATE_POST_COLL_SUCCESS = 2051;
}
